In [77]:
import pandas as pd
import numpy as np

In [88]:
mylist = [ "moustafa" , "Ahmed" , "moustafa" ]
pd.Series(mylist)

0    moustafa
1       Ahmed
2    moustafa
dtype: str

In [93]:
myIndex = [ 00 , 11 , 22 ]
pd.Series(myIndex,mylist)

moustafa     0
Ahmed       11
moustafa    22
dtype: int64

In [94]:
data = { "Moustafa":22,"Ali":21,"Mouhamed":23 }

df = pd.DataFrame(list(data.items()), columns=["Name", "Age"])
print(df)

       Name  Age
0  Moustafa   22
1       Ali   21
2  Mouhamed   23

In [96]:
dat = {"name":["Moustafa","Ali","Mouhamed"],"age":[22,21,23]}

In [97]:
dat

{'name': ['Moustafa', 'Ali', 'Mouhamed'], 'age': [22, 21, 23]}

In [99]:
s1 = { "china":350 ,"egypt":500,"uk":432,"USA":350}
s2 = { "USA":450,"egypt":200}
sales1 = pd.Series(s1)
sales2 = pd.Series(s2)
sales1 + sales2

USA      800.0
china      NaN
egypt    700.0
uk         NaN
dtype: float64

In [100]:
sales1.add(sales2,fill_value=0)

USA      800.0
china    350.0
egypt    700.0
uk       432.0
dtype: float64

In [109]:
arr = np.random.seed(11)
arr = np.random.randint(0,25,(5,5))
arr

array([[16, 17, 23, 13, 12],
       [ 1,  7, 18, 24, 13],
       [16,  0, 13, 12,  4],
       [ 2, 12,  1, 10,  5],
       [21,  7, 20, 17, 24]], dtype=int32)

In [110]:
columns = [ "one","tow","three","four","five" ]

In [112]:
rows = [ "one","tow","three","four","five" ]

In [123]:
table = pd.DataFrame(arr,index = rows,columns=columns,)
table

       one  tow  three  four  five
one     16   17     23    13    12
tow      1    7     18    24    13
three   16    0     13    12     4
four     2   12      1    10     5
five    21    7     20    17    24

In [130]:
pwd

'C:\\Users\\AIA\\email_classification'

In [126]:
d=pd.read_csv('dataset/email_spam.csv',encoding='latin1')

In [131]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 8674-5B48

 Directory of C:\Users\AIA\email_classification

04/22/2026  11:07 AM    <DIR>          .
04/19/2026  10:09 AM    <DIR>          ..
04/22/2026  09:53 AM    <DIR>          .ipynb_checkpoints
04/09/2026  01:12 PM    <DIR>          dataset
04/19/2026  12:04 PM            36,709 Naive_Bayes.ipynb
04/22/2026  11:07 AM             8,546 NumPy.ipynb
               2 File(s)         45,255 bytes
               4 Dir(s)   2,687,877,120 bytes free

In [133]:
d.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='str')

In [137]:
d.describe()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
count,5572,5572,50,12,6
unique,2,5169,43,10,5
top,ham,"Sorry, I'll call later","bt not his girlfrnd... G o o d n i g h t . . .@""","MK17 92H. 450Ppw 16""","GNT:-)"""
freq,4825,30,3,2,2

In [138]:
d.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [ ]:
d